/* Copy to config.js for local use. On GitHub, config.js is generated by
   .github/workflows/deploy.yml from repository secrets. */
window.SITE_CONFIG = {
  supabaseUrl: 'https://YOUR_PROJECT.supabase.co',
  supabaseAnonKey: 'sb_publishable_xxxxxxxx',
  adminUsername: 'agrin',
  // Either a plain password (local only) or a SHA-256 hex hash (used in deploys)
  adminPassword: 'your-admin-password'
  // adminPasswordHash: '<sha256 hex of the password>'
};
